//put puzzel pools in array
const idioms = [
    "Blessing In Disguise",
    "All In The Same Boat",
    "Barking Up The Wrong Tree",
    "Beat Around The Bush",
    "Bite The Bullet",
    "Bury The Hatchet",
    "By The Skin Of Your Teeth",
    "Call It A Day",
    "Cold Feet",
    "Cost An Arm And A Leg",
    "Cry Over Spilled Milk",
    "Cut Corners",
    "Drive Someone Up The Wall",
    "Silver Lining",
    "Face The Music",
    "Get A Taste Of Your Own Medicine",
    "Get The Ball Rolling",
    "Give Someone The Benefit Of The Doubt",
    "Go The Extra Mile",
    "Hit The Nail On The Head",
    "In The Heat Of The Moment",
    "A Piece Of Cake",
    "Keep Your Chin Up",
    "Kill Two Birds With One Stone",
    "Let The Cat Out Of The Bag",
    "Like A Fish Out Of Water",
    "Make A Long Story Short",
    "Miss The Boat",
    "Not My Cup Of Tea",
    "On Cloud Nine",
    "Once In A Blue Moon",
    "Out Of The Blue",
    "Over The Moon",
    "Put The Cart Before The Horse",
    "Raining Cats And Dogs",
    "Not Ring A Bell",
    "Rule Of Thumb",
    "Shoot Yourself In The Foot",
    "On The Fence",
    "Skeletons In The Closet",
    "Take A Rain Check",
    "The Ball Is In Your Court",
    "The Best Of Both Worlds",
    "Show Someone The Ropes",
    "The Whole Nine Yards",
    "Through Thick And Thin",
    "Throw In The Towel",
    "Turn A Blind Eye",
    "Under The Weather",
    "Off The Hook",
    "Up In The Air",
    "When It Rains It Pours",
    "Wrap Your Head Around Something",
    "Throw Someone For A Loop",
    "At The Drop Of A Hat",
    "At The End Of Your Rope",
    "Pipe Down",
    "Cross That Bridge When You Come To It",
    "Drop The Ball",
    "Elephant In The Room",
    "Get Off On The Wrong Foot",
    "Go Down In Flames",
    "Go With The Flow",
    "Hang In There",
    "In Hot Water",
    "Jump On The Bandwagon",
    "Kick The Bucket",
    "Swallow Something Hook Line And Sinker",
    "Show Your True Colors",
    "On Thin Ice",
    "Play It By Ear",
    "Save Your Breath",
    "Steal The Show",
    "Take It With A Grain Of Salt",
    "Clear As Mud",
    "Jump The Gun",
    "Get Your Wires Crossed",
    "Throw Caution To The Wind",
    "Lose Your Touch",
    "Off The Chain",
    "Eyeball It",
    "Spice Things Up",
    "Bring Home The Bacon",
    "Nip Something In The Bud",
    "The Last Straw",
    "A Whole New Ballgame",
    "Burn The Midnight Oil",
    "Between A Rock And A Hard Place",
    "Put Your Foot In Your Mouth",
    "Get A Grip",
    "Piece Of Work",
    "Put Someone On The Spot",
    "A Night Owl",
    "Has Seen Better Days",
    "Get Bent Out Of Shape",
    "Play Your Cards Right",
    "A Dime A Dozen",
    "All Ears"
]